"""Miscellaneous tools for handling things like chat, config, queues et al.

Modules:
    chat: Tools for chat based commands.
    config: Tools to handle configuration of the bot.
    get_emotes: Retrieve emote strings for the given channels.
    highlight_string: Tools to highlight a string with colour.
    song_queue: Tools for managing a random or prioritised request queue.
    text: Tools for formatting / manipulating text.
    timed_list: Manages a list erases its content after a specified time delay.
    tuple_list: A dict-like object that maintains ordering of key: value pairs.
    version: Autogenerated bot version.
"""
