"""Helper script to manage bot version number."""

import subprocess


def update_version():
    """
    Generate module containting bot version as per git.

    Check current bot version using git, then generate a .py module
    that the main function can load later.
    """
    output = '"""Autogenerated bot version"""'
    version = (
        subprocess.check_output("git describe --tags".split())
        .decode(encoding="utf-8")
        .replace("\n", "")
    )
    output += f'\nVERSION = "{version}"\n'
    with open("./tools/version.py", "w", encoding="utf-8") as _fd:
        _fd.write(output)


if __name__ == "__main__":
    update_version()
