"""Use git to generate a version file for the bot"""

import subprocess


def update_version():
    OUTPUT = '"""Autogenerated bot version"""'
    VERSION = (
        subprocess.check_output("git describe --tags".split())
        .decode(encoding="utf-8")
        .replace("\n", "")
    )
    OUTPUT += f'\nVERSION = "{VERSION}"\n'
    with open("./tools/version.py", "w", encoding="utf-8") as _fd:
        _fd.write(OUTPUT)
