"""Helper script to manage bot version number"""

import subprocess


def update_version():
    """
    Check current bot version using git, then generate a .py module
    that the main function can load later
    """

    output = '"""Autogenerated bot version"""'
    version = (
        subprocess.check_output("git describe --tags".split())
        .decode(encoding="utf-8")
        .replace("\n", "")
    )
    output += f'\nVERSION = "{version}"\n'
    with open("./tools/version.py", "w", encoding="utf-8") as _fd:
        _fd.write(output)
